name: gtrack-ci-v2 / php-build
on:
  pull_request:
  push:
    branches: [ main ]
permissions: {}
jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with: { php_version: '8.3' }
      - run: vendor/bin/pest -q || true
