name: gtrack-ci-v2
on:
  pull_request:
    branches: [ "main" ]
jobs:
  php-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: '8.3' }
      - run: |
          php -v
          composer --version || true
          echo "Skeleton only (step 1)"
