name: guard-readme
on:
  pull_request:
    branches: [ "main" ]
jobs:
  guard-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR body contains 'Docs updated'
        run: |
          body="${{ github.event.pull_request.body }}"
          echo "$body" | grep -qi "Docs updated" || (echo "PR body must contain 'Docs updated' block" && exit 1)
